### ISSUE TITLE
Variable applicationMobileActive (MonDossierWeb v3)

### ISSUE THREAD

**Issue by devwald** [EsupPortail/esup-mdw#2]
Bonjour,

Nous avons positionné à "false" la variable applicationMobileActive cependant la vue mobile est toujours proposée quand on se connecte avec un portable.

Une idée ?

Merci d'avance.

NB : nous sommes en version 1.1.8

**Comment by cdubois54** [comment]
Bonjour,

actuellement ce paramètre sert à bloquer 'temporairement' l'accès à la vue mobile de l'application.
Il ne permet pas d'ignorer la vue mobile et de toujours proposer la vue 'desktop'.
Cependant cela parait cohérent. Je vais donc prendre cela en compte dans la prochaine version de l'application.

Cordialement

**Comment by devwald** [comment]
Bonjour,

Merci.
Est-il possible facilement d'ignorer complètement la vue mobile ?
J'essaie de commenter différentes lignes puis de redéployer l'application sans succès.

Merci d'avance.

Cdt.

**Comment by cdubois54** [comment]
Je viens de push cette modification. Vous pouvez regarder sur le répo si c'est urgent.
Il faut commenter des lignes dans Initializer.java (activation de la servlet) et MdwUIProvider.java (proposition de la redirection)

**Comment by devwald** [comment]
Merci.
Je viens de tester la modification.
Je rencontre l'erreur suivante quand je consulte depuis mon téléphone : 

14:03:41.981 [ajp-nio-8009-exec-6] ERROR  org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[springVaadin] - Servlet.service() for servlet [springVaadin] in context with path [] threw exception [com.vaadin.server.ServiceException: java.lang.ClassCastException: Cannot cast fr.univlorraine.mondossierweb.MdwFallbackTouchkitUI to fr.univlorraine.mondossierweb.MainUI] with root cause
java.lang.ClassCastException: Cannot cast fr.univlorraine.mondossierweb.MdwFallbackTouchkitUI to fr.univlorraine.mondossierweb.MainUI
    at java.lang.Class.cast(Class.java:3369) ~[na:1.8.0_102]
    at com.vaadin.server.communication.UIInitHandler.getBrowserDetailsUI(UIInitHandler.java:191) ~[UIInitHandler.class:7.6.1]
    at com.vaadin.server.communication.UIInitHandler.synchronizedHandleRequest(UIInitHandler.java:74) ~[UIInitHandler.class:7.6.1]
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41) ~[SynchronizedRequestHandler.class:7.6.1]
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1409) ~[VaadinService.class:7.6.1]
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:364) ~[VaadinServlet.class:7.6.1]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:725) ~[tomcat8-servlet-api-8.0.14.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat8-websocket-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.springframework.mobile.device.DeviceResolverRequestFilter.doFilterInternal(DeviceResolverRequestFilter.java:60) ~[DeviceResolverRequestFilter.class:1.1.2.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[OncePerRequestFilter.class:4.1.6.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at fr.univlorraine.tools.logback.UserMdcServletFilter.doFilter(UserMdcServletFilter.java:49) ~[UserMdcServletFilter.class:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:316) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126) ~[FilterSecurityInterceptor.class:4.0.4.RELEASE]
    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90) ~[FilterSecurityInterceptor.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114) ~[ExceptionTranslationFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:122) ~[SessionManagementFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) ~[AnonymousAuthenticationFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169) ~[SecurityContextHolderAwareRequestFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:48) ~[RequestCacheAwareFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:205) ~[AbstractAuthenticationProcessingFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) ~[LogoutFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120) ~[LogoutFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:100) ~[SingleSignOutFilter.class:3.3.3]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64) ~[HeaderWriterFilter.class:4.0.4.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[OncePerRequestFilter.class:4.1.6.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91) ~[SecurityContextPersistenceFilter.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53) ~[WebAsyncManagerIntegrationFilter.class:4.0.4.RELEASE]
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[OncePerRequestFilter.class:4.1.6.RELEASE]
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330) ~[FilterChainProxy$VirtualFilterChain.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213) ~[FilterChainProxy.class:4.0.4.RELEASE]
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176) ~[FilterChainProxy.class:4.0.4.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344) ~[DelegatingFilterProxy.class:4.1.6.RELEASE]
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261) ~[DelegatingFilterProxy.class:4.1.6.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) ~[tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537) [tomcat8-catalina-8.0.14.jar:8.0.14]
    at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:827) [tomcat8-coyote-8.0.14.jar:8.0.14]
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658) [tomcat8-coyote-8.0.14.jar:8.0.14]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566) [tomcat8-coyote-8.0.14.jar:8.0.14]
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523) [tomcat8-coyote-8.0.14.jar:8.0.14]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat8-util-8.0.14.jar:8.0.14]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
tomcat8@v-resultats-2:/applis/resultats/esup-resultats-2$ 

Une idée ?

Merci d'avance.

**Comment by cdubois54** [comment]
Il doit manquer la modification du premier 'if' dans la méthode getUIClass de MdwUIProvider. 
Car normalement il ne doit pas tenter de rediriger vers MdwFallbackTouchkitUI.

A noter que ce test prend en compte un nouveau paramètre de context : 

`<Parameter name="startServletMobile" value="false" ></Parameter>`

Par contre, il y a peut être un soucis dans le cas contraire (on veut activer la proposition de redirection vers la vue mobile). faut que je peaufine ça.

**Comment by devwald** [comment]
Bonjour,

C'est OK.

Merci !

**Comment by cdubois54** [comment]
De rien. Cette amélioration sera incluse dans la prochaine version de l'application.
